### ISSUE TITLE
Please allow bump in Checkout-Ruby-SDK

### ISSUE THREAD

**Issue by fabn** [paypal/paypalhttp_ruby#24]
Please allow version bump in https://github.com/paypal/Checkout-Ruby-SDK otherwise changes made in #19 are not available to users. Alternatively could you release a `1.x` version of this gem with the deprecation solved?

**Comment by crookedneighbor** [comment]
The Checkout-Ruby-SDK is deprecated and no longer receiving updates. You are welcome to fork it (as @darkBuddha has done) and update it yourself, or collaborate on a community fork of the SDK.
